export const SAMPLE_QUESTIONS = [
    "Quy định về nồng độ cồn",
    "Mức phạt vượt đèn đỏ",
    "Quy định về tốc độ trong khu dân cư",
    "Bằng lái xe hạng A1 có thể lái xe gì",
    "Thủ tục đăng ký xe máy mới",
    "Mức phạt không đội mũ bảo hiểm",
    "Quy định về chuyển làn đường",
    "Mức phạt đi sai làn đường",
    "Thời hạn sử dụng bằng lái xe B2",
    "Quy định về đèn tín hiệu giao thông",
    "Mức phạt sử dụng điện thoại khi lái xe",
    "Quy định về giấy tờ cần mang khi tham gia giao thông",
    "Mức phạt không có giấy phép lái xe",
    "Quy định về dừng, đỗ xe trên đường phố",
    "Mức phạt đi ngược chiều",
    "Quy định về ưu tiên cho xe cứu thương, cứu hỏa",
    "Thủ tục đổi bằng lái xe quốc tế sang Việt Nam",
    "Quy định về độ tuổi được lái xe máy",
    "Mức phạt không bật đèn xe khi trời tối",
    "Quy định về xe quá tải, quá khổ",
    "Mức phạt không chấp hành hiệu lệnh cảnh sát giao thông",
    "Quy định về đội mũ bảo hiểm cho trẻ em",
    "Mức phạt vượt xe không đúng quy định",
    "Quy định về khoảng cách an toàn giữa các xe",
    "Mức phạt không nhường đường cho người đi bộ",
    "Quy định về xe đạp điện, xe máy điện",
    "Mức phạt chở quá số người quy định",
    "Quy định về biển báo giao thông quan trọng",
    "Mức phạt không gắn biển số xe",
    "Quy định về kiểm định an toàn kỹ thuật xe",
    "Mức phạt không mua bảo hiểm trách nhiệm dân sự",
    "Quy định về xử lý tai nạn giao thông",
    "Mức phạt vượt quá tốc độ cho phép",
    "Quy định về xe ô tô con, xe tải, xe khách",
    "Mức phạt không xi nhan khi chuyển hướng",
    "Quy định về làn đường dành cho xe buýt",
    "Mức phạt lấn chiếm vỉa hè, lòng đường",
    "Quy định về giấy tờ xe khi bị cảnh sát kiểm tra",
    "Mức phạt không đăng kiểm xe đúng hạn",
    "Quy định về sử dụng còi xe trong khu dân cư",
    "Mức phạt không dừng lại khi có tín hiệu dừng xe",
    "Quy định về tốc độ tối đa trên cao tốc",
    "Mức phạt vượt rào chắn đường sắt",
    "Quy định về xe ưu tiên khi tham gia giao thông",
    "Mức phạt không nhường đường cho xe ưu tiên",
    "Quy định về sử dụng đèn pha, đèn cốt",
    "Mức phạt không mang theo giấy đăng ký xe",
    "Quy định về xử phạt vi phạm hành chính giao thông",
    "Mức phạt không tuân thủ biển báo cấm",
    "Quy định về xe hợp đồng, xe công nghệ",
    "Mức phạt không đóng phí đường bộ",
    "Quy định về kiểm tra nồng độ cồn khi lái xe",
    "Mức phạt không chấp hành tín hiệu đèn giao thông",
    "Quy định về xe máy dưới 50cc",
    "Mức phạt không có bảo hiểm xe máy",
    "Quy định về xe tải vào thành phố",
    "Mức phạt không gắn gương chiếu hậu",
    "Quy định về xử lý khi bị tai nạn giao thông",
    "Mức phạt không đăng ký xe mới đúng hạn"
  ];