package sba.project.tuvanluatgiaothong.pojo;


import java.util.List;
import java.util.UUID;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import sba.project.tuvanluatgiaothong.utils.ChatItemJsonConverter;
import sba.project.tuvanluatgiaothong.utils.VietnamTimestampConverter;

@Data
@Builder
@DynamoDBTable(tableName = "swd392_chatbot_service_db")
@NoArgsConstructor
@AllArgsConstructor
public class    ChatHistory {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute(attributeName = "session_id")
    private String sessionId;

    @DynamoDBAttribute(attributeName = "user_id")
    private UUID userId;

    @DynamoDBAttribute(attributeName = "created_date")
    @DynamoDBTypeConverted(converter = VietnamTimestampConverter.class)
    private String createdDate;

    @DynamoDBAttribute(attributeName = "chat_title")
    private String chatTitle;

    @DynamoDBAttribute(attributeName = "model_alias")
    private String modelAlias;

    @DynamoDBAttribute(attributeName = "histories")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBTypeConverted(converter = ChatItemJsonConverter.class)
    private List<ChatItem> histories;

}
